
# Executable should be a full path
executable=/home/atatjer/src/plainLM/cluster/multi_gpu/condor.sh

# Hyperparmeters are specified in a YAML configuration file
config=/home/atatjer/src/plainLM/config/pythia10BT_LH/LH_05.yaml

# Queue as many jobs as points in the hyperaparameter grid
n_jobs=1

# Pass arguments to the executable
arguments = $(config) $(Process) $(Cluster)

# Logs
LOGS_DIR=/fast/atatjer/scalinglawsquantization/logs
error = $(LOGS_DIR)/err/job.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/job.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/job.$(Cluster).$(Process).log

# Job requirements
request_memory = 500000
request_cpus = 64
request_gpus = 8
# requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
# requirements = (TARGET.CUDACapability >= 8.0)  && (TARGET.CUDADeviceName != "NVIDIA A100-SXM4-40GB") && (TARGET.Machine != "i101.internal.cluster.is.localnet")
requirements = (TARGET.CUDACapability == 9.0) && (TARGET.Machine != "i101.internal.cluster.is.localnet") && (TARGET.Machine != "i103.internal.cluster.is.localnet")

queue $(n_jobs)